export const ADD_LOCATION = 'ADD_LOCATION';
export const LOAD_WEATHER_DATA_SUCCESS = 'LOAD_WEATHER_DATA_SUCCESS';
export const LOAD_FORECAST_DATA_SUCCESS = 'LOAD_FORECAST_DATA_SUCCESS';

export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
